### ISSUE TITLE
We need change package name again!

### ISSUE THREAD

**Issue by xcv58** [blue-systems-group/project.maybe.android.library#6]
Sadly, we have to change the package name again.

Because the Maybe Syntax introduce new keywords for java: `maybe` and `or` And keywords can't be part of package name.

Change `maybe` to `maybee` is okay, but looks not good.

Do you have any idea @SimplyRamya24

**Comment by SimplyRamya24** [comment]
how about changing from `edu.buffalo.cse.maybe.android.library` to `edu.buffalo.cse.android.maybelibrary`?

**Comment by xcv58** [comment]
It's reasonable.

**Comment by SimplyRamya24** [comment]
package name now set to `edu.buffalo.cse.android.maybelibrary` with commit "fix 6"

**Comment by xcv58** [comment]
According to: 
If any of the resulting package name components are keywords then append underscore to them.

https://books.google.com/books?id=mh-KAwAAQBAJ&lpg=PA133&ots=qgCZqREv10&dq=if%20any%20of%20the%20resulting%20package%20name%20components%20are%20keywords%20append%20an%20underscore%20to%20them&pg=PA133#v=onepage&q=if%20any%20of%20the%20resulting%20package%20name%20components%20are%20keywords%20append%20an%20underscore%20to%20them&f=false
