### ISSUE TITLE
Incorrect log url

### ISSUE THREAD

**Issue by xcv58** [blue-systems-group/project.maybe.android.library#7]
I got log:
`2015-09-14 12:20:13.650979469 13503 14216 D Maybe_Library: POST to https://maybe.xcv58.me/maybe-api-v1/logs/35823905193263/testing_inputs.maybe35823905193263/testing_inputs.maybe35823905193263/testing_inputs.maybe {"timestamp":1442247613650,"label":"1","logObject":[{"timestamp":1442247613600,"batterystatus":100,"logObject":{"label":"test","parameter2":"testAgain"},"deviceid":"35823905193263"}]}`

However, the url `https://maybe.xcv58.me/maybe-api-v1/logs/35823905193263/testing_inputs.maybe35823905193263/testing_inputs.maybe35823905193263/testing_inputs.maybe` is not correct.

@SimplyRamya24 you may need double check the url construct logic.

**Comment by SimplyRamya24** [comment]
Will fixed by fix #10
