### ISSUE TITLE
Weird build.gradle code

### ISSUE THREAD

**Issue by xcv58** [blue-systems-group/project.maybe.android.library#9]
@SimplyRamya24 in commit https://github.com/blue-systems-group/project.maybe.android.library/commit/bbdcda8958645874ceeca2a5e4b65ce7e2f41a3f?diff=unified you add such line in `demo/build.gradle`:
```groovy
main.java.srcDirs += 'src/main/java/org.phone_lab.maybe.library.demo/MainActivity'
```

Could you tell me why you did this? Because it looks like weird.

Otherwise, I'll delete it.

**Comment by SimplyRamya24** [comment]
Nothing related.
